/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './../packages/simplycms/admin-routes/routes/admin'
import { Route as StorefrontRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront'
import { Route as ProtectedRouteImport } from './../packages/simplycms/storefront-routes/routes/_protected'
import { Route as AuthIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/auth/index'
import { Route as AdminIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/index'
import { Route as StorefrontIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/index'
import { Route as AuthCallbackRouteImport } from './../packages/simplycms/storefront-routes/routes/auth/callback'
import { Route as ApiHealthRouteImport } from './../packages/simplycms/storefront-routes/routes/api/health'
import { Route as ApiGuestOrderRouteImport } from './../packages/simplycms/storefront-routes/routes/api/guest-order'
import { Route as StorefrontCheckoutRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/checkout'
import { Route as StorefrontCartRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/cart'
import { Route as AdminUsersIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/users/index'
import { Route as AdminUserCategoriesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/user-categories/index'
import { Route as AdminThemesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/themes/index'
import { Route as AdminShippingIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/index'
import { Route as AdminSettingsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/settings/index'
import { Route as AdminServicesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/services/index'
import { Route as AdminServiceRequestsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/service-requests/index'
import { Route as AdminSectionsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/sections/index'
import { Route as AdminReviewsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/reviews/index'
import { Route as AdminPropertiesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/properties/index'
import { Route as AdminProductsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/products/index'
import { Route as AdminPriceValidatorIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/price-validator/index'
import { Route as AdminPriceTypesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/price-types/index'
import { Route as AdminPluginsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/plugins/index'
import { Route as AdminOrdersIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/orders/index'
import { Route as AdminOrderStatusesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/order-statuses/index'
import { Route as AdminLanguagesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/languages/index'
import { Route as AdminDiscountsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/discounts/index'
import { Route as AdminBannersIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/banners/index'
import { Route as StorefrontPropertiesIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/properties/index'
import { Route as StorefrontCatalogIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/catalog/index'
import { Route as ProtectedProfileIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_protected/profile/index'
import { Route as AdminUsersUserIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/users/$userId'
import { Route as AdminUserCategoriesCategoryIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/user-categories/$categoryId'
import { Route as AdminSectionsSectionIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/sections/$sectionId'
import { Route as AdminReviewsReviewIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/reviews/$reviewId'
import { Route as AdminProductsProductIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/products/$productId'
import { Route as AdminPriceTypesPriceTypeIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/price-types/$priceTypeId'
import { Route as AdminOrdersOrderIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/orders/$orderId'
import { Route as AdminDiscountsDiscountIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/discounts/$discountId'
import { Route as AdminBannersBannerIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/banners/$bannerId'
import { Route as StorefrontOrderSuccessOrderIdRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/order-success/$orderId'
import { Route as ProtectedProfileSettingsRouteImport } from './../packages/simplycms/storefront-routes/routes/_protected/profile/settings'
import { Route as AdminUserCategoriesRulesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/user-categories/rules/index'
import { Route as AdminShippingZonesIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/zones/index'
import { Route as AdminShippingPickupPointsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/pickup-points/index'
import { Route as AdminShippingMethodsIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/methods/index'
import { Route as AdminPropertiesPropertyIdIndexRouteImport } from './../packages/simplycms/admin-routes/routes/admin/properties/$propertyId/index'
import { Route as StorefrontPropertiesPropertySlugIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/properties/$propertySlug/index'
import { Route as StorefrontCatalogSectionSlugIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/catalog/$sectionSlug/index'
import { Route as ProtectedProfileOrdersIndexRouteImport } from './../packages/simplycms/storefront-routes/routes/_protected/profile/orders/index'
import { Route as AdminUserCategoriesRulesRuleIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/user-categories/rules/$ruleId'
import { Route as AdminThemesThemeIdSettingsRouteImport } from './../packages/simplycms/admin-routes/routes/admin/themes/$themeId/settings'
import { Route as AdminShippingZonesZoneIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/zones/$zoneId'
import { Route as AdminShippingPickupPointsPointIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/pickup-points/$pointId'
import { Route as AdminShippingMethodsMethodIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/shipping/methods/$methodId'
import { Route as AdminPluginsPluginIdSettingsRouteImport } from './../packages/simplycms/admin-routes/routes/admin/plugins/$pluginId/settings'
import { Route as AdminDiscountsGroupsGroupIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/discounts/groups/$groupId'
import { Route as StorefrontPropertiesPropertySlugOptionSlugRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/properties/$propertySlug/$optionSlug'
import { Route as StorefrontCatalogSectionSlugProductSlugRouteImport } from './../packages/simplycms/storefront-routes/routes/_storefront/catalog/$sectionSlug/$productSlug'
import { Route as ProtectedProfileOrdersOrderIdRouteImport } from './../packages/simplycms/storefront-routes/routes/_protected/profile/orders/$orderId'
import { Route as AdminPropertiesPropertyIdOptionsOptionIdRouteImport } from './../packages/simplycms/admin-routes/routes/admin/properties/$propertyId/options/$optionId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRoute = StorefrontRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestOrderRoute = ApiGuestOrderRouteImport.update({
  id: '/api/guest-order',
  path: '/api/guest-order',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontCheckoutRoute = StorefrontCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCartRoute = StorefrontCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StorefrontRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserCategoriesIndexRoute =
  AdminUserCategoriesIndexRouteImport.update({
    id: '/user-categories/',
    path: '/user-categories/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminThemesIndexRoute = AdminThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingIndexRoute = AdminShippingIndexRouteImport.update({
  id: '/shipping/',
  path: '/shipping/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceRequestsIndexRoute =
  AdminServiceRequestsIndexRouteImport.update({
    id: '/service-requests/',
    path: '/service-requests/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSectionsIndexRoute = AdminSectionsIndexRouteImport.update({
  id: '/sections/',
  path: '/sections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPriceValidatorIndexRoute =
  AdminPriceValidatorIndexRouteImport.update({
    id: '/price-validator/',
    path: '/price-validator/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPriceTypesIndexRoute = AdminPriceTypesIndexRouteImport.update({
  id: '/price-types/',
  path: '/price-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPluginsIndexRoute = AdminPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderStatusesIndexRoute = AdminOrderStatusesIndexRouteImport.update({
  id: '/order-statuses/',
  path: '/order-statuses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesIndexRoute = AdminLanguagesIndexRouteImport.update({
  id: '/languages/',
  path: '/languages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersIndexRoute = AdminBannersIndexRouteImport.update({
  id: '/banners/',
  path: '/banners/',
  getParentRoute: () => AdminRoute,
} as any)
const StorefrontPropertiesIndexRoute =
  StorefrontPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontCatalogIndexRoute = StorefrontCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => StorefrontRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserCategoriesCategoryIdRoute =
  AdminUserCategoriesCategoryIdRouteImport.update({
    id: '/user-categories/$categoryId',
    path: '/user-categories/$categoryId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSectionsSectionIdRoute = AdminSectionsSectionIdRouteImport.update({
  id: '/sections/$sectionId',
  path: '/sections/$sectionId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsReviewIdRoute = AdminReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPriceTypesPriceTypeIdRoute =
  AdminPriceTypesPriceTypeIdRouteImport.update({
    id: '/price-types/$priceTypeId',
    path: '/price-types/$priceTypeId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsDiscountIdRoute =
  AdminDiscountsDiscountIdRouteImport.update({
    id: '/discounts/$discountId',
    path: '/discounts/$discountId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBannersBannerIdRoute = AdminBannersBannerIdRouteImport.update({
  id: '/banners/$bannerId',
  path: '/banners/$bannerId',
  getParentRoute: () => AdminRoute,
} as any)
const StorefrontOrderSuccessOrderIdRoute =
  StorefrontOrderSuccessOrderIdRouteImport.update({
    id: '/order-success/$orderId',
    path: '/order-success/$orderId',
    getParentRoute: () => StorefrontRoute,
  } as any)
const ProtectedProfileSettingsRoute =
  ProtectedProfileSettingsRouteImport.update({
    id: '/profile/settings',
    path: '/profile/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AdminUserCategoriesRulesIndexRoute =
  AdminUserCategoriesRulesIndexRouteImport.update({
    id: '/user-categories/rules/',
    path: '/user-categories/rules/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingZonesIndexRoute = AdminShippingZonesIndexRouteImport.update({
  id: '/shipping/zones/',
  path: '/shipping/zones/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingPickupPointsIndexRoute =
  AdminShippingPickupPointsIndexRouteImport.update({
    id: '/shipping/pickup-points/',
    path: '/shipping/pickup-points/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingMethodsIndexRoute =
  AdminShippingMethodsIndexRouteImport.update({
    id: '/shipping/methods/',
    path: '/shipping/methods/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPropertiesPropertyIdIndexRoute =
  AdminPropertiesPropertyIdIndexRouteImport.update({
    id: '/properties/$propertyId/',
    path: '/properties/$propertyId/',
    getParentRoute: () => AdminRoute,
  } as any)
const StorefrontPropertiesPropertySlugIndexRoute =
  StorefrontPropertiesPropertySlugIndexRouteImport.update({
    id: '/properties/$propertySlug/',
    path: '/properties/$propertySlug/',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontCatalogSectionSlugIndexRoute =
  StorefrontCatalogSectionSlugIndexRouteImport.update({
    id: '/catalog/$sectionSlug/',
    path: '/catalog/$sectionSlug/',
    getParentRoute: () => StorefrontRoute,
  } as any)
const ProtectedProfileOrdersIndexRoute =
  ProtectedProfileOrdersIndexRouteImport.update({
    id: '/profile/orders/',
    path: '/profile/orders/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AdminUserCategoriesRulesRuleIdRoute =
  AdminUserCategoriesRulesRuleIdRouteImport.update({
    id: '/user-categories/rules/$ruleId',
    path: '/user-categories/rules/$ruleId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminThemesThemeIdSettingsRoute =
  AdminThemesThemeIdSettingsRouteImport.update({
    id: '/themes/$themeId/settings',
    path: '/themes/$themeId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingZonesZoneIdRoute =
  AdminShippingZonesZoneIdRouteImport.update({
    id: '/shipping/zones/$zoneId',
    path: '/shipping/zones/$zoneId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingPickupPointsPointIdRoute =
  AdminShippingPickupPointsPointIdRouteImport.update({
    id: '/shipping/pickup-points/$pointId',
    path: '/shipping/pickup-points/$pointId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingMethodsMethodIdRoute =
  AdminShippingMethodsMethodIdRouteImport.update({
    id: '/shipping/methods/$methodId',
    path: '/shipping/methods/$methodId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPluginsPluginIdSettingsRoute =
  AdminPluginsPluginIdSettingsRouteImport.update({
    id: '/plugins/$pluginId/settings',
    path: '/plugins/$pluginId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDiscountsGroupsGroupIdRoute =
  AdminDiscountsGroupsGroupIdRouteImport.update({
    id: '/discounts/groups/$groupId',
    path: '/discounts/groups/$groupId',
    getParentRoute: () => AdminRoute,
  } as any)
const StorefrontPropertiesPropertySlugOptionSlugRoute =
  StorefrontPropertiesPropertySlugOptionSlugRouteImport.update({
    id: '/properties/$propertySlug/$optionSlug',
    path: '/properties/$propertySlug/$optionSlug',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontCatalogSectionSlugProductSlugRoute =
  StorefrontCatalogSectionSlugProductSlugRouteImport.update({
    id: '/catalog/$sectionSlug/$productSlug',
    path: '/catalog/$sectionSlug/$productSlug',
    getParentRoute: () => StorefrontRoute,
  } as any)
const ProtectedProfileOrdersOrderIdRoute =
  ProtectedProfileOrdersOrderIdRouteImport.update({
    id: '/profile/orders/$orderId',
    path: '/profile/orders/$orderId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AdminPropertiesPropertyIdOptionsOptionIdRoute =
  AdminPropertiesPropertyIdOptionsOptionIdRouteImport.update({
    id: '/properties/$propertyId/options/$optionId',
    path: '/properties/$propertyId/options/$optionId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StorefrontIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof StorefrontCartRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/api/guest-order': typeof ApiGuestOrderRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/order-success/$orderId': typeof StorefrontOrderSuccessOrderIdRoute
  '/admin/banners/$bannerId': typeof AdminBannersBannerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/price-types/$priceTypeId': typeof AdminPriceTypesPriceTypeIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/reviews/$reviewId': typeof AdminReviewsReviewIdRoute
  '/admin/sections/$sectionId': typeof AdminSectionsSectionIdRoute
  '/admin/user-categories/$categoryId': typeof AdminUserCategoriesCategoryIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/catalog/': typeof StorefrontCatalogIndexRoute
  '/properties/': typeof StorefrontPropertiesIndexRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/languages/': typeof AdminLanguagesIndexRoute
  '/admin/order-statuses/': typeof AdminOrderStatusesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/plugins/': typeof AdminPluginsIndexRoute
  '/admin/price-types/': typeof AdminPriceTypesIndexRoute
  '/admin/price-validator/': typeof AdminPriceValidatorIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/sections/': typeof AdminSectionsIndexRoute
  '/admin/service-requests/': typeof AdminServiceRequestsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shipping/': typeof AdminShippingIndexRoute
  '/admin/themes/': typeof AdminThemesIndexRoute
  '/admin/user-categories/': typeof AdminUserCategoriesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/profile/orders/$orderId': typeof ProtectedProfileOrdersOrderIdRoute
  '/catalog/$sectionSlug/$productSlug': typeof StorefrontCatalogSectionSlugProductSlugRoute
  '/properties/$propertySlug/$optionSlug': typeof StorefrontPropertiesPropertySlugOptionSlugRoute
  '/admin/discounts/groups/$groupId': typeof AdminDiscountsGroupsGroupIdRoute
  '/admin/plugins/$pluginId/settings': typeof AdminPluginsPluginIdSettingsRoute
  '/admin/shipping/methods/$methodId': typeof AdminShippingMethodsMethodIdRoute
  '/admin/shipping/pickup-points/$pointId': typeof AdminShippingPickupPointsPointIdRoute
  '/admin/shipping/zones/$zoneId': typeof AdminShippingZonesZoneIdRoute
  '/admin/themes/$themeId/settings': typeof AdminThemesThemeIdSettingsRoute
  '/admin/user-categories/rules/$ruleId': typeof AdminUserCategoriesRulesRuleIdRoute
  '/profile/orders/': typeof ProtectedProfileOrdersIndexRoute
  '/catalog/$sectionSlug/': typeof StorefrontCatalogSectionSlugIndexRoute
  '/properties/$propertySlug/': typeof StorefrontPropertiesPropertySlugIndexRoute
  '/admin/properties/$propertyId/': typeof AdminPropertiesPropertyIdIndexRoute
  '/admin/shipping/methods/': typeof AdminShippingMethodsIndexRoute
  '/admin/shipping/pickup-points/': typeof AdminShippingPickupPointsIndexRoute
  '/admin/shipping/zones/': typeof AdminShippingZonesIndexRoute
  '/admin/user-categories/rules/': typeof AdminUserCategoriesRulesIndexRoute
  '/admin/properties/$propertyId/options/$optionId': typeof AdminPropertiesPropertyIdOptionsOptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof StorefrontIndexRoute
  '/cart': typeof StorefrontCartRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/api/guest-order': typeof ApiGuestOrderRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/order-success/$orderId': typeof StorefrontOrderSuccessOrderIdRoute
  '/admin/banners/$bannerId': typeof AdminBannersBannerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/price-types/$priceTypeId': typeof AdminPriceTypesPriceTypeIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/reviews/$reviewId': typeof AdminReviewsReviewIdRoute
  '/admin/sections/$sectionId': typeof AdminSectionsSectionIdRoute
  '/admin/user-categories/$categoryId': typeof AdminUserCategoriesCategoryIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/catalog': typeof StorefrontCatalogIndexRoute
  '/properties': typeof StorefrontPropertiesIndexRoute
  '/admin/banners': typeof AdminBannersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/languages': typeof AdminLanguagesIndexRoute
  '/admin/order-statuses': typeof AdminOrderStatusesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/plugins': typeof AdminPluginsIndexRoute
  '/admin/price-types': typeof AdminPriceTypesIndexRoute
  '/admin/price-validator': typeof AdminPriceValidatorIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/sections': typeof AdminSectionsIndexRoute
  '/admin/service-requests': typeof AdminServiceRequestsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/shipping': typeof AdminShippingIndexRoute
  '/admin/themes': typeof AdminThemesIndexRoute
  '/admin/user-categories': typeof AdminUserCategoriesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/profile/orders/$orderId': typeof ProtectedProfileOrdersOrderIdRoute
  '/catalog/$sectionSlug/$productSlug': typeof StorefrontCatalogSectionSlugProductSlugRoute
  '/properties/$propertySlug/$optionSlug': typeof StorefrontPropertiesPropertySlugOptionSlugRoute
  '/admin/discounts/groups/$groupId': typeof AdminDiscountsGroupsGroupIdRoute
  '/admin/plugins/$pluginId/settings': typeof AdminPluginsPluginIdSettingsRoute
  '/admin/shipping/methods/$methodId': typeof AdminShippingMethodsMethodIdRoute
  '/admin/shipping/pickup-points/$pointId': typeof AdminShippingPickupPointsPointIdRoute
  '/admin/shipping/zones/$zoneId': typeof AdminShippingZonesZoneIdRoute
  '/admin/themes/$themeId/settings': typeof AdminThemesThemeIdSettingsRoute
  '/admin/user-categories/rules/$ruleId': typeof AdminUserCategoriesRulesRuleIdRoute
  '/profile/orders': typeof ProtectedProfileOrdersIndexRoute
  '/catalog/$sectionSlug': typeof StorefrontCatalogSectionSlugIndexRoute
  '/properties/$propertySlug': typeof StorefrontPropertiesPropertySlugIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdIndexRoute
  '/admin/shipping/methods': typeof AdminShippingMethodsIndexRoute
  '/admin/shipping/pickup-points': typeof AdminShippingPickupPointsIndexRoute
  '/admin/shipping/zones': typeof AdminShippingZonesIndexRoute
  '/admin/user-categories/rules': typeof AdminUserCategoriesRulesIndexRoute
  '/admin/properties/$propertyId/options/$optionId': typeof AdminPropertiesPropertyIdOptionsOptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_storefront': typeof StorefrontRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_storefront/cart': typeof StorefrontCartRoute
  '/_storefront/checkout': typeof StorefrontCheckoutRoute
  '/api/guest-order': typeof ApiGuestOrderRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_storefront/': typeof StorefrontIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/profile/settings': typeof ProtectedProfileSettingsRoute
  '/_storefront/order-success/$orderId': typeof StorefrontOrderSuccessOrderIdRoute
  '/admin/banners/$bannerId': typeof AdminBannersBannerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/price-types/$priceTypeId': typeof AdminPriceTypesPriceTypeIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/reviews/$reviewId': typeof AdminReviewsReviewIdRoute
  '/admin/sections/$sectionId': typeof AdminSectionsSectionIdRoute
  '/admin/user-categories/$categoryId': typeof AdminUserCategoriesCategoryIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_storefront/catalog/': typeof StorefrontCatalogIndexRoute
  '/_storefront/properties/': typeof StorefrontPropertiesIndexRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/languages/': typeof AdminLanguagesIndexRoute
  '/admin/order-statuses/': typeof AdminOrderStatusesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/plugins/': typeof AdminPluginsIndexRoute
  '/admin/price-types/': typeof AdminPriceTypesIndexRoute
  '/admin/price-validator/': typeof AdminPriceValidatorIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/sections/': typeof AdminSectionsIndexRoute
  '/admin/service-requests/': typeof AdminServiceRequestsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shipping/': typeof AdminShippingIndexRoute
  '/admin/themes/': typeof AdminThemesIndexRoute
  '/admin/user-categories/': typeof AdminUserCategoriesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_protected/profile/orders/$orderId': typeof ProtectedProfileOrdersOrderIdRoute
  '/_storefront/catalog/$sectionSlug/$productSlug': typeof StorefrontCatalogSectionSlugProductSlugRoute
  '/_storefront/properties/$propertySlug/$optionSlug': typeof StorefrontPropertiesPropertySlugOptionSlugRoute
  '/admin/discounts/groups/$groupId': typeof AdminDiscountsGroupsGroupIdRoute
  '/admin/plugins/$pluginId/settings': typeof AdminPluginsPluginIdSettingsRoute
  '/admin/shipping/methods/$methodId': typeof AdminShippingMethodsMethodIdRoute
  '/admin/shipping/pickup-points/$pointId': typeof AdminShippingPickupPointsPointIdRoute
  '/admin/shipping/zones/$zoneId': typeof AdminShippingZonesZoneIdRoute
  '/admin/themes/$themeId/settings': typeof AdminThemesThemeIdSettingsRoute
  '/admin/user-categories/rules/$ruleId': typeof AdminUserCategoriesRulesRuleIdRoute
  '/_protected/profile/orders/': typeof ProtectedProfileOrdersIndexRoute
  '/_storefront/catalog/$sectionSlug/': typeof StorefrontCatalogSectionSlugIndexRoute
  '/_storefront/properties/$propertySlug/': typeof StorefrontPropertiesPropertySlugIndexRoute
  '/admin/properties/$propertyId/': typeof AdminPropertiesPropertyIdIndexRoute
  '/admin/shipping/methods/': typeof AdminShippingMethodsIndexRoute
  '/admin/shipping/pickup-points/': typeof AdminShippingPickupPointsIndexRoute
  '/admin/shipping/zones/': typeof AdminShippingZonesIndexRoute
  '/admin/user-categories/rules/': typeof AdminUserCategoriesRulesIndexRoute
  '/admin/properties/$propertyId/options/$optionId': typeof AdminPropertiesPropertyIdOptionsOptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/api/guest-order'
    | '/api/health'
    | '/auth/callback'
    | '/admin/'
    | '/auth/'
    | '/profile/settings'
    | '/order-success/$orderId'
    | '/admin/banners/$bannerId'
    | '/admin/discounts/$discountId'
    | '/admin/orders/$orderId'
    | '/admin/price-types/$priceTypeId'
    | '/admin/products/$productId'
    | '/admin/reviews/$reviewId'
    | '/admin/sections/$sectionId'
    | '/admin/user-categories/$categoryId'
    | '/admin/users/$userId'
    | '/profile/'
    | '/catalog/'
    | '/properties/'
    | '/admin/banners/'
    | '/admin/discounts/'
    | '/admin/languages/'
    | '/admin/order-statuses/'
    | '/admin/orders/'
    | '/admin/plugins/'
    | '/admin/price-types/'
    | '/admin/price-validator/'
    | '/admin/products/'
    | '/admin/properties/'
    | '/admin/reviews/'
    | '/admin/sections/'
    | '/admin/service-requests/'
    | '/admin/services/'
    | '/admin/settings/'
    | '/admin/shipping/'
    | '/admin/themes/'
    | '/admin/user-categories/'
    | '/admin/users/'
    | '/profile/orders/$orderId'
    | '/catalog/$sectionSlug/$productSlug'
    | '/properties/$propertySlug/$optionSlug'
    | '/admin/discounts/groups/$groupId'
    | '/admin/plugins/$pluginId/settings'
    | '/admin/shipping/methods/$methodId'
    | '/admin/shipping/pickup-points/$pointId'
    | '/admin/shipping/zones/$zoneId'
    | '/admin/themes/$themeId/settings'
    | '/admin/user-categories/rules/$ruleId'
    | '/profile/orders/'
    | '/catalog/$sectionSlug/'
    | '/properties/$propertySlug/'
    | '/admin/properties/$propertyId/'
    | '/admin/shipping/methods/'
    | '/admin/shipping/pickup-points/'
    | '/admin/shipping/zones/'
    | '/admin/user-categories/rules/'
    | '/admin/properties/$propertyId/options/$optionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/api/guest-order'
    | '/api/health'
    | '/auth/callback'
    | '/admin'
    | '/auth'
    | '/profile/settings'
    | '/order-success/$orderId'
    | '/admin/banners/$bannerId'
    | '/admin/discounts/$discountId'
    | '/admin/orders/$orderId'
    | '/admin/price-types/$priceTypeId'
    | '/admin/products/$productId'
    | '/admin/reviews/$reviewId'
    | '/admin/sections/$sectionId'
    | '/admin/user-categories/$categoryId'
    | '/admin/users/$userId'
    | '/profile'
    | '/catalog'
    | '/properties'
    | '/admin/banners'
    | '/admin/discounts'
    | '/admin/languages'
    | '/admin/order-statuses'
    | '/admin/orders'
    | '/admin/plugins'
    | '/admin/price-types'
    | '/admin/price-validator'
    | '/admin/products'
    | '/admin/properties'
    | '/admin/reviews'
    | '/admin/sections'
    | '/admin/service-requests'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/themes'
    | '/admin/user-categories'
    | '/admin/users'
    | '/profile/orders/$orderId'
    | '/catalog/$sectionSlug/$productSlug'
    | '/properties/$propertySlug/$optionSlug'
    | '/admin/discounts/groups/$groupId'
    | '/admin/plugins/$pluginId/settings'
    | '/admin/shipping/methods/$methodId'
    | '/admin/shipping/pickup-points/$pointId'
    | '/admin/shipping/zones/$zoneId'
    | '/admin/themes/$themeId/settings'
    | '/admin/user-categories/rules/$ruleId'
    | '/profile/orders'
    | '/catalog/$sectionSlug'
    | '/properties/$propertySlug'
    | '/admin/properties/$propertyId'
    | '/admin/shipping/methods'
    | '/admin/shipping/pickup-points'
    | '/admin/shipping/zones'
    | '/admin/user-categories/rules'
    | '/admin/properties/$propertyId/options/$optionId'
  id:
    | '__root__'
    | '/_protected'
    | '/_storefront'
    | '/admin'
    | '/_storefront/cart'
    | '/_storefront/checkout'
    | '/api/guest-order'
    | '/api/health'
    | '/auth/callback'
    | '/_storefront/'
    | '/admin/'
    | '/auth/'
    | '/_protected/profile/settings'
    | '/_storefront/order-success/$orderId'
    | '/admin/banners/$bannerId'
    | '/admin/discounts/$discountId'
    | '/admin/orders/$orderId'
    | '/admin/price-types/$priceTypeId'
    | '/admin/products/$productId'
    | '/admin/reviews/$reviewId'
    | '/admin/sections/$sectionId'
    | '/admin/user-categories/$categoryId'
    | '/admin/users/$userId'
    | '/_protected/profile/'
    | '/_storefront/catalog/'
    | '/_storefront/properties/'
    | '/admin/banners/'
    | '/admin/discounts/'
    | '/admin/languages/'
    | '/admin/order-statuses/'
    | '/admin/orders/'
    | '/admin/plugins/'
    | '/admin/price-types/'
    | '/admin/price-validator/'
    | '/admin/products/'
    | '/admin/properties/'
    | '/admin/reviews/'
    | '/admin/sections/'
    | '/admin/service-requests/'
    | '/admin/services/'
    | '/admin/settings/'
    | '/admin/shipping/'
    | '/admin/themes/'
    | '/admin/user-categories/'
    | '/admin/users/'
    | '/_protected/profile/orders/$orderId'
    | '/_storefront/catalog/$sectionSlug/$productSlug'
    | '/_storefront/properties/$propertySlug/$optionSlug'
    | '/admin/discounts/groups/$groupId'
    | '/admin/plugins/$pluginId/settings'
    | '/admin/shipping/methods/$methodId'
    | '/admin/shipping/pickup-points/$pointId'
    | '/admin/shipping/zones/$zoneId'
    | '/admin/themes/$themeId/settings'
    | '/admin/user-categories/rules/$ruleId'
    | '/_protected/profile/orders/'
    | '/_storefront/catalog/$sectionSlug/'
    | '/_storefront/properties/$propertySlug/'
    | '/admin/properties/$propertyId/'
    | '/admin/shipping/methods/'
    | '/admin/shipping/pickup-points/'
    | '/admin/shipping/zones/'
    | '/admin/user-categories/rules/'
    | '/admin/properties/$propertyId/options/$optionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  StorefrontRoute: typeof StorefrontRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiGuestOrderRoute: typeof ApiGuestOrderRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-order': {
      id: '/api/guest-order'
      path: '/api/guest-order'
      fullPath: '/api/guest-order'
      preLoaderRoute: typeof ApiGuestOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront/checkout': {
      id: '/_storefront/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StorefrontCheckoutRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/cart': {
      id: '/_storefront/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StorefrontCartRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user-categories/': {
      id: '/admin/user-categories/'
      path: '/user-categories'
      fullPath: '/admin/user-categories/'
      preLoaderRoute: typeof AdminUserCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes/': {
      id: '/admin/themes/'
      path: '/themes'
      fullPath: '/admin/themes/'
      preLoaderRoute: typeof AdminThemesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/': {
      id: '/admin/shipping/'
      path: '/shipping'
      fullPath: '/admin/shipping/'
      preLoaderRoute: typeof AdminShippingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-requests/': {
      id: '/admin/service-requests/'
      path: '/service-requests'
      fullPath: '/admin/service-requests/'
      preLoaderRoute: typeof AdminServiceRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections/': {
      id: '/admin/sections/'
      path: '/sections'
      fullPath: '/admin/sections/'
      preLoaderRoute: typeof AdminSectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/price-validator/': {
      id: '/admin/price-validator/'
      path: '/price-validator'
      fullPath: '/admin/price-validator/'
      preLoaderRoute: typeof AdminPriceValidatorIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/price-types/': {
      id: '/admin/price-types/'
      path: '/price-types'
      fullPath: '/admin/price-types/'
      preLoaderRoute: typeof AdminPriceTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugins/': {
      id: '/admin/plugins/'
      path: '/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AdminPluginsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order-statuses/': {
      id: '/admin/order-statuses/'
      path: '/order-statuses'
      fullPath: '/admin/order-statuses/'
      preLoaderRoute: typeof AdminOrderStatusesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages/': {
      id: '/admin/languages/'
      path: '/languages'
      fullPath: '/admin/languages/'
      preLoaderRoute: typeof AdminLanguagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners/': {
      id: '/admin/banners/'
      path: '/banners'
      fullPath: '/admin/banners/'
      preLoaderRoute: typeof AdminBannersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/properties/': {
      id: '/_storefront/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof StorefrontPropertiesIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/catalog/': {
      id: '/_storefront/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof StorefrontCatalogIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user-categories/$categoryId': {
      id: '/admin/user-categories/$categoryId'
      path: '/user-categories/$categoryId'
      fullPath: '/admin/user-categories/$categoryId'
      preLoaderRoute: typeof AdminUserCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections/$sectionId': {
      id: '/admin/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/admin/sections/$sectionId'
      preLoaderRoute: typeof AdminSectionsSectionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/$reviewId': {
      id: '/admin/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/admin/reviews/$reviewId'
      preLoaderRoute: typeof AdminReviewsReviewIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/price-types/$priceTypeId': {
      id: '/admin/price-types/$priceTypeId'
      path: '/price-types/$priceTypeId'
      fullPath: '/admin/price-types/$priceTypeId'
      preLoaderRoute: typeof AdminPriceTypesPriceTypeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/$discountId': {
      id: '/admin/discounts/$discountId'
      path: '/discounts/$discountId'
      fullPath: '/admin/discounts/$discountId'
      preLoaderRoute: typeof AdminDiscountsDiscountIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners/$bannerId': {
      id: '/admin/banners/$bannerId'
      path: '/banners/$bannerId'
      fullPath: '/admin/banners/$bannerId'
      preLoaderRoute: typeof AdminBannersBannerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/order-success/$orderId': {
      id: '/_storefront/order-success/$orderId'
      path: '/order-success/$orderId'
      fullPath: '/order-success/$orderId'
      preLoaderRoute: typeof StorefrontOrderSuccessOrderIdRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_protected/profile/settings': {
      id: '/_protected/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProtectedProfileSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/admin/user-categories/rules/': {
      id: '/admin/user-categories/rules/'
      path: '/user-categories/rules'
      fullPath: '/admin/user-categories/rules/'
      preLoaderRoute: typeof AdminUserCategoriesRulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/zones/': {
      id: '/admin/shipping/zones/'
      path: '/shipping/zones'
      fullPath: '/admin/shipping/zones/'
      preLoaderRoute: typeof AdminShippingZonesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/pickup-points/': {
      id: '/admin/shipping/pickup-points/'
      path: '/shipping/pickup-points'
      fullPath: '/admin/shipping/pickup-points/'
      preLoaderRoute: typeof AdminShippingPickupPointsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/methods/': {
      id: '/admin/shipping/methods/'
      path: '/shipping/methods'
      fullPath: '/admin/shipping/methods/'
      preLoaderRoute: typeof AdminShippingMethodsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties/$propertyId/': {
      id: '/admin/properties/$propertyId/'
      path: '/properties/$propertyId'
      fullPath: '/admin/properties/$propertyId/'
      preLoaderRoute: typeof AdminPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/properties/$propertySlug/': {
      id: '/_storefront/properties/$propertySlug/'
      path: '/properties/$propertySlug'
      fullPath: '/properties/$propertySlug/'
      preLoaderRoute: typeof StorefrontPropertiesPropertySlugIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/catalog/$sectionSlug/': {
      id: '/_storefront/catalog/$sectionSlug/'
      path: '/catalog/$sectionSlug'
      fullPath: '/catalog/$sectionSlug/'
      preLoaderRoute: typeof StorefrontCatalogSectionSlugIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_protected/profile/orders/': {
      id: '/_protected/profile/orders/'
      path: '/profile/orders'
      fullPath: '/profile/orders/'
      preLoaderRoute: typeof ProtectedProfileOrdersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/admin/user-categories/rules/$ruleId': {
      id: '/admin/user-categories/rules/$ruleId'
      path: '/user-categories/rules/$ruleId'
      fullPath: '/admin/user-categories/rules/$ruleId'
      preLoaderRoute: typeof AdminUserCategoriesRulesRuleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes/$themeId/settings': {
      id: '/admin/themes/$themeId/settings'
      path: '/themes/$themeId/settings'
      fullPath: '/admin/themes/$themeId/settings'
      preLoaderRoute: typeof AdminThemesThemeIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/zones/$zoneId': {
      id: '/admin/shipping/zones/$zoneId'
      path: '/shipping/zones/$zoneId'
      fullPath: '/admin/shipping/zones/$zoneId'
      preLoaderRoute: typeof AdminShippingZonesZoneIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/pickup-points/$pointId': {
      id: '/admin/shipping/pickup-points/$pointId'
      path: '/shipping/pickup-points/$pointId'
      fullPath: '/admin/shipping/pickup-points/$pointId'
      preLoaderRoute: typeof AdminShippingPickupPointsPointIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping/methods/$methodId': {
      id: '/admin/shipping/methods/$methodId'
      path: '/shipping/methods/$methodId'
      fullPath: '/admin/shipping/methods/$methodId'
      preLoaderRoute: typeof AdminShippingMethodsMethodIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugins/$pluginId/settings': {
      id: '/admin/plugins/$pluginId/settings'
      path: '/plugins/$pluginId/settings'
      fullPath: '/admin/plugins/$pluginId/settings'
      preLoaderRoute: typeof AdminPluginsPluginIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/groups/$groupId': {
      id: '/admin/discounts/groups/$groupId'
      path: '/discounts/groups/$groupId'
      fullPath: '/admin/discounts/groups/$groupId'
      preLoaderRoute: typeof AdminDiscountsGroupsGroupIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/properties/$propertySlug/$optionSlug': {
      id: '/_storefront/properties/$propertySlug/$optionSlug'
      path: '/properties/$propertySlug/$optionSlug'
      fullPath: '/properties/$propertySlug/$optionSlug'
      preLoaderRoute: typeof StorefrontPropertiesPropertySlugOptionSlugRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/catalog/$sectionSlug/$productSlug': {
      id: '/_storefront/catalog/$sectionSlug/$productSlug'
      path: '/catalog/$sectionSlug/$productSlug'
      fullPath: '/catalog/$sectionSlug/$productSlug'
      preLoaderRoute: typeof StorefrontCatalogSectionSlugProductSlugRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_protected/profile/orders/$orderId': {
      id: '/_protected/profile/orders/$orderId'
      path: '/profile/orders/$orderId'
      fullPath: '/profile/orders/$orderId'
      preLoaderRoute: typeof ProtectedProfileOrdersOrderIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/admin/properties/$propertyId/options/$optionId': {
      id: '/admin/properties/$propertyId/options/$optionId'
      path: '/properties/$propertyId/options/$optionId'
      fullPath: '/admin/properties/$propertyId/options/$optionId'
      preLoaderRoute: typeof AdminPropertiesPropertyIdOptionsOptionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProfileSettingsRoute: typeof ProtectedProfileSettingsRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedProfileOrdersOrderIdRoute: typeof ProtectedProfileOrdersOrderIdRoute
  ProtectedProfileOrdersIndexRoute: typeof ProtectedProfileOrdersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileSettingsRoute: ProtectedProfileSettingsRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedProfileOrdersOrderIdRoute: ProtectedProfileOrdersOrderIdRoute,
  ProtectedProfileOrdersIndexRoute: ProtectedProfileOrdersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface StorefrontRouteChildren {
  StorefrontCartRoute: typeof StorefrontCartRoute
  StorefrontCheckoutRoute: typeof StorefrontCheckoutRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontOrderSuccessOrderIdRoute: typeof StorefrontOrderSuccessOrderIdRoute
  StorefrontCatalogIndexRoute: typeof StorefrontCatalogIndexRoute
  StorefrontPropertiesIndexRoute: typeof StorefrontPropertiesIndexRoute
  StorefrontCatalogSectionSlugProductSlugRoute: typeof StorefrontCatalogSectionSlugProductSlugRoute
  StorefrontPropertiesPropertySlugOptionSlugRoute: typeof StorefrontPropertiesPropertySlugOptionSlugRoute
  StorefrontCatalogSectionSlugIndexRoute: typeof StorefrontCatalogSectionSlugIndexRoute
  StorefrontPropertiesPropertySlugIndexRoute: typeof StorefrontPropertiesPropertySlugIndexRoute
}

const StorefrontRouteChildren: StorefrontRouteChildren = {
  StorefrontCartRoute: StorefrontCartRoute,
  StorefrontCheckoutRoute: StorefrontCheckoutRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontOrderSuccessOrderIdRoute: StorefrontOrderSuccessOrderIdRoute,
  StorefrontCatalogIndexRoute: StorefrontCatalogIndexRoute,
  StorefrontPropertiesIndexRoute: StorefrontPropertiesIndexRoute,
  StorefrontCatalogSectionSlugProductSlugRoute:
    StorefrontCatalogSectionSlugProductSlugRoute,
  StorefrontPropertiesPropertySlugOptionSlugRoute:
    StorefrontPropertiesPropertySlugOptionSlugRoute,
  StorefrontCatalogSectionSlugIndexRoute:
    StorefrontCatalogSectionSlugIndexRoute,
  StorefrontPropertiesPropertySlugIndexRoute:
    StorefrontPropertiesPropertySlugIndexRoute,
}

const StorefrontRouteWithChildren = StorefrontRoute._addFileChildren(
  StorefrontRouteChildren,
)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBannersBannerIdRoute: typeof AdminBannersBannerIdRoute
  AdminDiscountsDiscountIdRoute: typeof AdminDiscountsDiscountIdRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminPriceTypesPriceTypeIdRoute: typeof AdminPriceTypesPriceTypeIdRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminReviewsReviewIdRoute: typeof AdminReviewsReviewIdRoute
  AdminSectionsSectionIdRoute: typeof AdminSectionsSectionIdRoute
  AdminUserCategoriesCategoryIdRoute: typeof AdminUserCategoriesCategoryIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminBannersIndexRoute: typeof AdminBannersIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminLanguagesIndexRoute: typeof AdminLanguagesIndexRoute
  AdminOrderStatusesIndexRoute: typeof AdminOrderStatusesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPluginsIndexRoute: typeof AdminPluginsIndexRoute
  AdminPriceTypesIndexRoute: typeof AdminPriceTypesIndexRoute
  AdminPriceValidatorIndexRoute: typeof AdminPriceValidatorIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminSectionsIndexRoute: typeof AdminSectionsIndexRoute
  AdminServiceRequestsIndexRoute: typeof AdminServiceRequestsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminShippingIndexRoute: typeof AdminShippingIndexRoute
  AdminThemesIndexRoute: typeof AdminThemesIndexRoute
  AdminUserCategoriesIndexRoute: typeof AdminUserCategoriesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminDiscountsGroupsGroupIdRoute: typeof AdminDiscountsGroupsGroupIdRoute
  AdminPluginsPluginIdSettingsRoute: typeof AdminPluginsPluginIdSettingsRoute
  AdminShippingMethodsMethodIdRoute: typeof AdminShippingMethodsMethodIdRoute
  AdminShippingPickupPointsPointIdRoute: typeof AdminShippingPickupPointsPointIdRoute
  AdminShippingZonesZoneIdRoute: typeof AdminShippingZonesZoneIdRoute
  AdminThemesThemeIdSettingsRoute: typeof AdminThemesThemeIdSettingsRoute
  AdminUserCategoriesRulesRuleIdRoute: typeof AdminUserCategoriesRulesRuleIdRoute
  AdminPropertiesPropertyIdIndexRoute: typeof AdminPropertiesPropertyIdIndexRoute
  AdminShippingMethodsIndexRoute: typeof AdminShippingMethodsIndexRoute
  AdminShippingPickupPointsIndexRoute: typeof AdminShippingPickupPointsIndexRoute
  AdminShippingZonesIndexRoute: typeof AdminShippingZonesIndexRoute
  AdminUserCategoriesRulesIndexRoute: typeof AdminUserCategoriesRulesIndexRoute
  AdminPropertiesPropertyIdOptionsOptionIdRoute: typeof AdminPropertiesPropertyIdOptionsOptionIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBannersBannerIdRoute: AdminBannersBannerIdRoute,
  AdminDiscountsDiscountIdRoute: AdminDiscountsDiscountIdRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminPriceTypesPriceTypeIdRoute: AdminPriceTypesPriceTypeIdRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminReviewsReviewIdRoute: AdminReviewsReviewIdRoute,
  AdminSectionsSectionIdRoute: AdminSectionsSectionIdRoute,
  AdminUserCategoriesCategoryIdRoute: AdminUserCategoriesCategoryIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminBannersIndexRoute: AdminBannersIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminLanguagesIndexRoute: AdminLanguagesIndexRoute,
  AdminOrderStatusesIndexRoute: AdminOrderStatusesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPluginsIndexRoute: AdminPluginsIndexRoute,
  AdminPriceTypesIndexRoute: AdminPriceTypesIndexRoute,
  AdminPriceValidatorIndexRoute: AdminPriceValidatorIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminSectionsIndexRoute: AdminSectionsIndexRoute,
  AdminServiceRequestsIndexRoute: AdminServiceRequestsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminShippingIndexRoute: AdminShippingIndexRoute,
  AdminThemesIndexRoute: AdminThemesIndexRoute,
  AdminUserCategoriesIndexRoute: AdminUserCategoriesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminDiscountsGroupsGroupIdRoute: AdminDiscountsGroupsGroupIdRoute,
  AdminPluginsPluginIdSettingsRoute: AdminPluginsPluginIdSettingsRoute,
  AdminShippingMethodsMethodIdRoute: AdminShippingMethodsMethodIdRoute,
  AdminShippingPickupPointsPointIdRoute: AdminShippingPickupPointsPointIdRoute,
  AdminShippingZonesZoneIdRoute: AdminShippingZonesZoneIdRoute,
  AdminThemesThemeIdSettingsRoute: AdminThemesThemeIdSettingsRoute,
  AdminUserCategoriesRulesRuleIdRoute: AdminUserCategoriesRulesRuleIdRoute,
  AdminPropertiesPropertyIdIndexRoute: AdminPropertiesPropertyIdIndexRoute,
  AdminShippingMethodsIndexRoute: AdminShippingMethodsIndexRoute,
  AdminShippingPickupPointsIndexRoute: AdminShippingPickupPointsIndexRoute,
  AdminShippingZonesIndexRoute: AdminShippingZonesIndexRoute,
  AdminUserCategoriesRulesIndexRoute: AdminUserCategoriesRulesIndexRoute,
  AdminPropertiesPropertyIdOptionsOptionIdRoute:
    AdminPropertiesPropertyIdOptionsOptionIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  StorefrontRoute: StorefrontRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiGuestOrderRoute: ApiGuestOrderRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
