name: CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check PHP Version
        run: php -v
      - name: Load Composer Deps
        run: |
          composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader
          composer validate
      - name: Set up application
        run: |
          cp .env.testing .env
          php artisan key:generate
          cp .env .env.testing
      - name: Set up applicatio
        run: |
          vendor/bin/phpunit
