name: CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check PHP Version
        run: php -v
      - name: Load Composer Deps
        run: |
          composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader
          composer validate
      - name: Set up application
        run: |
          cp .env.testing .env
          php artisan key:generate
          cp .env .env.testing
      - name: Run PHPUnit
          run: vendor/bin/phpunit
      - name: Upgrade chrome driver
          run: php artisan dusk:chrome-driver
      - name: Start Chrome Driver
          run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
      - name: Run Laravel Server
          run: php artisan serve > /dev/null 2>&1 &
      - name: Run dusk tests
          run: php artisan dusk
